@contentType = application/json
@token = ikvwwqea5zikvasdfasdfwwqea5zi2swrTEEd
@baseurl = http://localhost:8000/api/v1


GET {{baseurl}}/users

###
GET {{baseurl}}/user/3

###
POST {{baseurl}}/user
Content-Type: {{contentType}
Authentication: Bearer {{token}}

{
    "name": "sutin deno",
    "country": "thailand"
}

###
PUT {{baseurl}}/user/2
Content-Type: {{contentType}
Authentication: Bearer {{token}}

{
    "name": "sutin deno RestAPI",
    "country": "thailand"
}

###
DELETE {{baseurl}}/user/3